apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scribe.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scribe.labels" . | nindent 4 }}
automountServiceAccountToken: true
