apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
data:
  generate.sh: |
    {{- tpl (.Files.Get "static/generate-kubeconfig.sh") . | nindent 4}}
