# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: false
  high_level_summary_in_walkthrough: true
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true
  poem: false
  abort_on_close: true
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - "chore(main): release"
