checks:
  exclude:
    - "no-read-only-root-fs"
    - "run-as-non-root"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "non-existent-service-account" # TODO(scribe): validate why it fails
