{{- $tag := default .Chart.AppVersion (default .Values.kubernetes.version .Values.kubeApiserver.image.tag) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kubeApiserver.replicaCount }}
  selector:
    matchLabels:
      {{- include "hosted-control-plane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.kubeApiserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hosted-control-plane.labels" . | nindent 8 }}
        {{- include "hosted-control-plane.apiserver.labels" . | nindent 8 }}
        {{- with .Values.kubeApiserver.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hosted-control-plane.fullname" . }}
      securityContext:
        {{- toYaml .Values.kubeApiserver.podSecurityContext | nindent 8 }}
      containers:
        - name: kube-apiserver
          command:
            - kube-apiserver
          args:
            - --v={{ .Values.kubeApiserver.verbosity }}
            - --client-ca-file=/etc/pki/kubernetes/ca.crt
            - --tls-cert-file=/etc/pki/kube-apiserver/tls.crt
            - --tls-private-key-file=/etc/pki/kube-apiserver/tls.key
            - --service-account-key-file=/etc/pki/service-accounts/tls.crt
            - --service-account-signing-key-file=/etc/pki/service-accounts/tls.key
            - --service-account-issuer=https://kubernetes.default.svc.cluster.local
            - --etcd-cafile=/etc/pki/etcd/ca.crt
            - --etcd-certfile=/etc/pki/etcd/tls.crt
            - --etcd-keyfile=/etc/pki/etcd/tls.key
            - --etcd-servers=https://{{ include "hosted-control-plane.fullname" . }}-kine.{{ .Release.Namespace }}.svc.cluster.local:2379
            - --authorization-mode=Node,RBAC
            - --service-cluster-ip-range={{ .Values.kubernetes.serviceIPRange }}
            - --egress-selector-config-file=/etc/konnectivity/egress-selector-configuration.yaml
          securityContext:
            {{- toYaml .Values.kubeApiserver.securityContext | nindent 12 }}
          image: "{{ .Values.kubeApiserver.image.repository }}:{{ $tag }}"
          imagePullPolicy: {{ .Values.kubeApiserver.image.pullPolicy }}
          ports:
            - name: server
              containerPort: 6443
              protocol: TCP
          volumeMounts:
            - name: etcd
              readOnly: true
              mountPath: /etc/pki/etcd
            - name: apiserver-tls
              readOnly: true
              mountPath: /etc/pki/kube-apiserver
            - name: root-ca
              readOnly: true
              mountPath: /etc/pki/kubernetes
            - name: service-accounts-cert
              readOnly: true
              mountPath: /etc/pki/service-accounts
            - name: configs
              readOnly: true
              mountPath: /etc/konnectivity
          startupProbe:
            httpGet:
              path: /livez
              port: server
              scheme: HTTPS
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: server
              scheme: HTTPS
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: server
              scheme: HTTPS
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.kubeApiserver.resources | nindent 12 }}
        - name: konnectivity
          command:
            - /proxy-server
          args:
            - --v={{ .Values.konnectivity.server.verbosity }}
            - --mode=grpc
            - --cluster-cert=/etc/pki/kubernetes/tls.crt
            - --cluster-key=/etc/pki/kubernetes/tls.key
            - --uds-name=/etc/kubernetes/konnectivity-server/konnectivity-server.socket
            - --delete-existing-uds-file=true
            - --server-port=0
            - --agent-port=8132
            - --admin-port=8133
            - --health-port=8134
            - --agent-namespace=kube-system
            - --agent-service-account=konnectivity-agent
            - --kubeconfig=/etc/kubernetes/value
            - --authentication-audience=system:konnectivity-server
          securityContext:
            {{- toYaml .Values.konnectivity.server.securityContext | nindent 12 }}
          image: "{{ .Values.konnectivity.server.image.repository }}:{{ .Values.konnectivity.server.image.tag }}"
          imagePullPolicy: {{ .Values.konnectivity.server.image.pullPolicy }}
          ports:
            - name: agent
              containerPort: 8132
              protocol: TCP
            - name: admin
              containerPort: 8133
              protocol: TCP
            - name: health
              containerPort: 8134
              protocol: TCP
          volumeMounts:
            - name: uds
              mountPath: /etc/kubernetes/konnectivity-server
            - name: root-ca
              readOnly: true
              mountPath: /etc/pki/kubernetes
            - name: kubeconfig
              readOnly: true
              mountPath: /etc/kubernetes
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
              scheme: HTTP
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: health
              scheme: HTTP
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.konnectivity.server.resources | nindent 12 }}
      volumes:
        - name: etcd
          secret:
            secretName: {{ include "hosted-control-plane.fullname" . }}-etcd-client
            defaultMode: 420
        - name: apiserver-tls
          secret:
            secretName: {{ include "hosted-control-plane.fullname" . }}-api-server
            defaultMode: 420
        - name: root-ca
          secret:
            secretName: {{ include "hosted-control-plane.fullname" . }}-ca
            defaultMode: 420
        - name: service-accounts-cert
          secret:
            secretName: {{ include "hosted-control-plane.fullname" . }}-sa
            defaultMode: 420
        - name: kubeconfig
          secret:
            secretName: {{ include "hosted-control-plane.fullname" . }}-konnectivity-kubeconfig
            defaultMode: 420
        - name: uds
          emptyDir: {}
        - name: configs
          configMap:
            name: {{ include "hosted-control-plane.fullname" . }}-configs-{{ .Release.Revision }}
      {{- with .Values.kubeApiserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeApiserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeApiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
