apiVersion: v1
kind: Service
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
spec:
  ports:
    - name: server
      port: 6443
      protocol: TCP
      targetPort: server
  selector:
    {{- include "hosted-control-plane.selectorLabels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
