apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-installer-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
data:
  manifests.yaml: |
    {{- tpl (.Files.Get "static/konnectivity/rbac.yaml") . | nindent 4}}
    {{- tpl (.Files.Get "static/konnectivity/daemonset.yaml") . | nindent 4}}
  install.sh: |
    {{- tpl (.Files.Get "static/konnectivity/install-konnectivity.sh") . | nindent 4}}
