{{- if .Values.config.create -}}
{{- $host := default "localhost" .Values.ingress.host }}
{{- $provider := .Values.database.provider | default "sqlite" }}
{{- if not (or (eq $provider "sqlite") (eq $provider "postgres")) }}
  {{- fail (printf "Invalid database provider: %s. .Values.database.provider must be 'sqlite' or 'postgres'." $provider) }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocket-id.config" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  TRUST_PROXY: "true"
  CADDY_DISABLED: "false"
  CADDY_PORT: "80"
  PORT: "3000"
  BACKEND_PORT: "8000"
  HOST: "0.0.0.0"
  INTERNAL_BACKEND_URL: "http://localhost:8080"
  UPDATE_CHECK_DISABLED: "true"
  UPLOAD_PATH: "data/uploads"
  KEYS_PATH: "data/keys"
  GEOLITE_DB_PATH: "data/GeoLite2-City.mmdb"
  PUBLIC_UI_CONFIG_DISABLED: "{{ .Values.config.ui.enabled }}"
  PUBLIC_APP_URL: "https://{{ $host }}"
  DB_PROVIDER: "{{ $provider }}"
  GEOLITE_DB_URL: "{{ .Values.geoliteDatabaseURL }}"
  {{- if not .Values.publicUI.useDefaults }}
  APP_NAME: "{{ .Values.publicUI.settings.app.appName }}"
  SESSION_DURATION: "{{ .Values.publicUI.settings.app.sessionDuration }}"
  EMAILS_VERIFIED: "{{ .Values.publicUI.settings.app.emailsVerified }}"
  ALLOW_OWN_ACCOUNT_EDIT: "{{ .Values.publicUI.settings.app.allowOwnAccountEdit }}"
  DISABLE_ANIMATIONS: "{{ .Values.publicUI.settings.app.disableAnimations }}"
  SMTP_HOST: "{{ .Values.publicUI.settings.smtp.host }}"
  SMTP_PORT: "{{ .Values.publicUI.settings.smtp.port }}"
  SMTP_FROM: "{{ .Values.publicUI.settings.smtp.from }}"
  SMTP_USER: "{{ .Values.publicUI.settings.smtp.user }}"
  SMTP_PASSWORD: "{{ .Values.publicUI.settings.smtp.password }}"
  SMTP_TLS: "{{ .Values.publicUI.settings.smtp.tls }}"
  SMTP_SKIP_CERT_VERIFY: "{{ .Values.publicUI.settings.smtp.skipCertVerify }}"
  EMAIL_LOGIN_NOTIFICATION_ENABLED: "{{ .Values.publicUI.settings.email.loginNotificationEnabled }}"
  EMAIL_ONE_TIME_ACCESS_ENABLED: "{{ .Values.publicUI.settings.email.oneTimeAccessEnabled }}"
  LDAP_ENABLED: "{{ .Values.publicUI.settings.ldap.enabled }}"
  LDAP_URL: "{{ .Values.publicUI.settings.ldap.url }}"
  LDAP_BIND_DN: "{{ .Values.publicUI.settings.ldap.bindDN }}"
  LDAP_BIND_PASSWORD: "{{ .Values.publicUI.settings.ldap.bindPassword }}"
  LDAP_BASE: "{{ .Values.publicUI.settings.ldap.base }}"
  LDAP_USER_SEARCH_FILTER: "{{ .Values.publicUI.settings.ldap.userSearchFilter }}"
  LDAP_USER_GROUP_SEARCH_FILTER: "{{ .Values.publicUI.settings.ldap.userGroupSearchFilter }}"
  LDAP_SKIP_CERT_VERIFY: "{{ .Values.publicUI.settings.ldap.skipCertVerify }}"
  LDAP_ATTRIBUTE_USER_UNIQUE_IDENTIFIER: "{{ .Values.publicUI.settings.ldap.attributes.user.uniqueIdentifier }}"
  LDAP_ATTRIBUTE_USER_USERNAME: "{{ .Values.publicUI.settings.ldap.attributes.user.username }}"
  LDAP_ATTRIBUTE_USER_EMAIL: "{{ .Values.publicUI.settings.ldap.attributes.user.email }}"
  LDAP_ATTRIBUTE_USER_FIRST_NAME: "{{ .Values.publicUI.settings.ldap.attributes.user.firstName }}"
  LDAP_ATTRIBUTE_USER_LAST_NAME: "{{ .Values.publicUI.settings.ldap.attributes.user.lastName }}"
  LDAP_ATTRIBUTE_USER_PROFILE_PICTURE: "{{ .Values.publicUI.settings.ldap.attributes.user.profilePicture }}"
  LDAP_ATTRIBUTE_GROUP_MEMBER: "{{ .Values.publicUI.settings.ldap.attributes.group.member }}"
  LDAP_ATTRIBUTE_GROUP_UNIQUE_IDENTIFIER: "{{ .Values.publicUI.settings.ldap.attributes.group.uniqueIdentifier }}"
  LDAP_ATTRIBUTE_GROUP_NAME: "{{ .Values.publicUI.settings.ldap.attributes.group.name }}"
  LDAP_ATTRIBUTE_ADMIN_GROUP: "{{ .Values.publicUI.settings.ldap.attributes.group.adminGroup }}"
  {{- end }}
{{- end }}
