apiVersion: v1
kind: Service
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-kine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.kine.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
    - name: kine
      port: 2379
      protocol: TCP
      targetPort: kine
  selector:
    {{- include "hosted-control-plane.selectorLabels" . | nindent 4 }}
    {{- include "hosted-control-plane.kine.labels" . | nindent 4 }}
