---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-metrics-auth-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hosted-control-plane.fullname" . }}-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: {{ include "hosted-control-plane.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-metrics-auth-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-metrics-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-generator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-generator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hosted-control-plane.fullname" . }}-generator
subjects:
  - kind: ServiceAccount
    name: {{ include "hosted-control-plane.fullname" . }}-generator
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-generator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.apiserver.labels" . | nindent 4 }}
