apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omada-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omada-controller.labels" . | nindent 4 }}
data:
  SSL_CERT_NAME: "tls.crt"
  SSL_KEY_NAME: "tls.key"

  MANAGE_HTTP_PORT: "{{ .Values.config.manageHttpPort | int | default 8088 }}"
  MANAGE_HTTPS_PORT: "{{ .Values.config.manageHttpsPort | int | default 8043 }}"
  PORTAL_HTTP_PORT: "{{ .Values.config.portalHttpPort | int | default 8888 }}"
  PORTAL_HTTPS_PORT: "{{ .Values.config.portalHttpsPort | int | default 8843 }}"
  PORT_ADOPT_V1: "{{ .Values.config.adoptV1Port | int | default 29812 }}"
  PORT_APP_DISCOVERY: "{{ .Values.config.appDiscoveryPort | int | default 27001 }}"
  PORT_DISCOVERY: "{{ .Values.config.discoveryPort | int | default 29810 }}"
  PORT_MANAGER_V1: "{{ .Values.config.managerV1Port | int | default 29811 }}"
  PORT_MANAGER_V2: "{{ .Values.config.managerV2Port | int | default 29814 }}"
  PORT_TRANSFER_V2: "{{ .Values.config.transferV2Port | int | default 29815 }}"
  PORT_RTTY: "{{ .Values.config.rttyPort | int | default 29816 }}"
  PORT_UPGRADE_V1: "{{ .Values.config.upgradeV1Port | int | default 29813 }}"
  # TODO: OLT port

  PUID: "{{ .Values.config.puid | int | default 508 }}"
  PGID: "{{ .Values.config.pgid | int | default 508 }}"
  PUSERNAME: "{{ .Values.config.pusername | default "omada" }}"
  PGROUP: "{{ .Values.config.pgroup | default "omada" }}"

  ROOTLESS: "{{ .Values.config.rootless | ternary "true" "false" }}"
  SHOW_SERVER_LOGS: "{{ .Values.config.showServerLogs | ternary "true" "false" }}"
  SHOW_MONGODB_LOGS: "{{ .Values.config.showMongoDbLogs | ternary "true" "false" }}"
  SKIP_USERLAND_KERNEL_CHECK: "{{ .Values.config.skipUserlandKernelCheck | ternary "true" "false" }}"
  SMALL_FILES: "{{ .Values.config.smallFiles | ternary "true" "false" }}"
  TLS_1_11_ENABLED: "{{ .Values.config.tlsLegacyEnabled | ternary "true" "false" }}"
  TZ: "{{ .Values.config.timezone | default "Etc/UTC" }}"
