apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podvm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podvm.labels" . | nindent 4 }}
data:
  vmconfig.json: |
    {
      "boot-source": {
        "kernel_image_path": "/path/to/kernel",
        "boot_args": "$KERNEL_BOOT_ARGS"
      },
      "drives": [
        {
          "drive_id": "rootfs",
          "path_on_host": "hello-rootfs.ext4",
          "is_root_device": true,
          "is_read_only": false
        }
      ],
      "network-interfaces": [
          {
              "iface_id": "eth0",
              "guest_mac": "$FC_MAC",
              "host_dev_name": "$TAP_DEV"
          }
      ],
      "machine-config": {
        "vcpu_count": 2,
        "mem_size_mib": 1024,
        "ht_enabled": false
      }
    }
