apiVersion: v1
kind: Pod
metadata:
  name: {{ include "podvm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podvm.labels" . | nindent 4 }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # serviceAccountName: {{ include "podvm.fullname" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - name: firecracker
      command:
        - firecracker
      args:
        - --no-api
        - --config-file
        - /etc/firecracker/vmconfig.json
      securityContext:
        {{- toYaml .Values.firecracker.securityContext | nindent 8 }}
      image: "{{ .Values.firecracker.image.repository }}:{{ .Values.firecracker.image.tag }}"
      imagePullPolicy: {{ .Values.firecracker.image.pullPolicy }}
      volumeMounts:
      {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: vmconfig
          mountPath: /etc/firecracker
        - name: kernel
          mountPath: "{{- include "podvm.kernelDir" . }}"
        - name: rootfs
          mountPath: "{{- include "podvm.rootfsDir" . }}"
      resources:
        requests:
          {{- with (index .Values.config "machine-config") }}
          memory: "{{ printf "%dMi" (int .mem_size_mib) }}"
          cpu: "{{ printf "%d" (int .vcpu_count) }}"
          {{- end }}
          {{- printf "%s: '1'" .Values.kvm.name | nindent 10 }}
          {{- printf "%s: '1'" .Values.tun.name | nindent 10 }}
        limits:
          {{- with (index .Values.config "machine-config") }}
          memory: "{{ printf "%dMi" (int .mem_size_mib) }}"
          {{- end }}
          {{- printf "%s: '1'" .Values.kvm.name | nindent 10 }}
          {{- printf "%s: '1'" .Values.tun.name | nindent 10 }}
  volumes:
  {{- with .Values.volumes }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    - name: vmconfig
      configMap:
        name: {{ include "podvm.fullname" . }}
    - name: kernel
      image:
        name: "{{ .Values.kernel.image.repository }}:{{ .Values.kernel.image.tag }}"
    - name: rootfs
      image:
        name: "{{ .Values.rootfs.image.repository }}:{{ .Values.rootfs.image.tag }}"
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
