---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: konnectivity-agent
  namespace: kube-system
  labels:
    app.kubernetes.io/name: konnectivity-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: konnectivity-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: konnectivity-agent
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      hostNetwork: true
      serviceAccountName: konnectivity-agent
      containers:
        - name: konnectivity
          image: ${KONNECTIVITY_AGENT}
          imagePullPolicy: ${KONNECTIVITY_AGENT_PULL_POLICY}
          command: 
            - /proxy-agent
          args:
            - --v=${VERBOSITY}
            - --logtostderr=true
            - --ca-cert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --proxy-server-host=${PROXY_HOST}
            - --proxy-server-port=8132
            - --service-account-token-path=/var/run/secrets/tokens/konnectivity-agent-token
          ports:
            - name: health
              containerPort: 8093
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
              scheme: HTTP
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
              scheme: HTTP
            initialDelaySeconds: 30
          volumeMounts:
            - name: konnectivity-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
      volumes:
        - name: konnectivity-token
          projected:
            sources:
              - serviceAccountToken:
                  path: konnectivity-agent-token
                  audience: system:konnectivity-server
