apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podvm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podvm.labels" . | nindent 4 }}
data:
  vmconfig.json: |
    {{ .Values.config | toJson }}