apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omada-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omada-controller.labels" . | nindent 4 }}
data:
  SSL_CERT_NAME: "tls.crt"
  SSL_KEY_NAME: "tls.key"

  TZ: "{{ .Values.config.timezone | default "Etc/UTC" }}"
  SMALL_FILES: "{{ .Values.config.smallFiles | ternary "true" "false" }}"
  SKIP_USERLAND_KERNEL_CHECK: "{{ .Values.config.skipUserlandKernelCheck | ternary "true" "false" }}"

  PUID: "{{ .Values.config.puid | int | default 508 }}"
  PGID: "{{ .Values.config.pgid | int | default 508 }}"
  PUSERNAME: "{{ .Values.config.pusername | default "omada" }}"
  PGROUP: "{{ .Values.config.pgroup | default "omada" }}"
  ROOTLESS: "{{ .Values.config.rootless | ternary "true" "false" }}"

  SHOW_SERVER_LOGS: "{{ .Values.config.showServerLogs | ternary "true" "false" }}"
  SHOW_MONGODB_LOGS: "{{ .Values.config.showMongoDbLogs | ternary "true" "false" }}"
  TLS_1_11_ENABLED: "{{ .Values.config.tlsLegacyEnabled | ternary "true" "false" }}"
