---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-scheduler-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: Issuer
    name: {{ include "hosted-control-plane.fullname" . }}-ca
  commonName: system:kube-scheduler
  subject:
    organizations:
      - system:kube-scheduler
  duration: 8760h
  renewBefore: 720h
  secretName: {{ include "hosted-control-plane.fullname" . }}-scheduler-cert
  secretTemplate:
    labels: 
      {{- include "hosted-control-plane.selectorLabels" . | nindent 6 }}
  usages:
    - digital signature
    - key encipherment
    - client auth
