apiVersion: v1
kind: Service
metadata:
  name: {{ include "hosted-control-plane.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hosted-control-plane.labels" . | nindent 4 }}
    {{- include "hosted-control-plane.scheduler.labels" . | nindent 4 }}
spec:
  ports:
    - name: self
      port: 10259
      protocol: TCP
      targetPort: self
  selector:
    {{- include "hosted-control-plane.selectorLabels" . | nindent 4 }}
    {{- include "hosted-control-plane.scheduler.labels" . | nindent 4 }}
