{{- if .Values.trigger.enabled }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ksvm.fullname" . }}-trigger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksvm.labels" . | nindent 4 }}
rules:
- apiGroups: ["migration.k8s.io"]
  resources: ["storagestates"]
  verbs: ["watch", "get", "list", "delete", "create", "update"]
- apiGroups: ["migration.k8s.io"]
  resources: ["storageversionmigrations"]
  verbs: ["watch", "get", "list", "delete", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ksvm.fullname" . }}-trigger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksvm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ksvm.fullname" . }}-trigger
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "ksvm.fullname" . }}-trigger
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if .Values.migrator.enabled }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ksvm.fullname" . }}-migrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksvm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ksvm.fullname" . }}-migrator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
