---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ksvm.fullname" . }}-trigger
  labels:
    {{- include "ksvm.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ksvm.fullname" . }}-migrator
  labels:
    {{- include "ksvm.labels" . | nindent 4 }}
automountServiceAccountToken: true
