apiVersion: v1
kind: Service
metadata:
  name: {{ include "ksvm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksvm.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: probes
      port: 8080
      protocol: TCP
      targetPort: probes
  selector:
    {{- include "ksvm.selectorLabels" . | nindent 4 }}
