apiVersion: v2
name: kube-storage-version-migrator
description: |
  This tool migrates stored data in etcd to the latest storage version.
type: application
version: 0.0.1
appVersion: "v0.0.5"
maintainers:
  - name: Mateusz Urbanek
    email: matueusz.urbanek.98@gmail.com
    url: http://linkedin.com/in/urbanekmateusz
