name: command

on:
  issue_comment:
    types:
      - created

jobs:
  process-comment:
    if: startsWith(github.event.comment.body, '/ci ')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: dkershner6/reaction-action@v2
        with:
          token: ${{ secrets.PAT }}
          reaction: 'eyes'
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.COMMIT_SIGNING }}" > ~/.ssh/signing_key
          chmod 600 ~/.ssh/signing_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/signing_key
          git config user.name shanduur-auto
          git config user.email 75127809+shanduur-auto@users.noreply.github.com
          git config gpg.format ssh
          git config user.signingkey ~/.ssh/signing_key
          git config commit.gpgsign true
      - id: extract_info
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./hack/comment.sh "${{ github.event.comment.body }}" "${{ github.event.issue.number }}" "${GITHUB_ENV}"
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          BRANCH_NAME=$(gh pr view $PR_NUMBER --json headRefName --jq '.headRefName')
          git fetch origin $BRANCH_NAME
          git checkout $BRANCH_NAME
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: |
          make ci CHART=anza-labs/${{ env.chart_name }} VERSION=${{ env.chart_version }}
      - run: |
          git add .
          git commit -sm "fix: generated chart ${{ env.chart_name }} version ${{ env.chart_version }}" || echo "No changes to commit"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ env.branch }}
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.PAT }}
          labels: do-not-merge
