name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Prepare GPG key
        env:
          GPG_KEYRING_BASE64: ${{ secrets.GPG_KEYRING_BASE64 }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./hack/gpg.sh \
            "${GPG_KEYRING_BASE64}" \
            "${GPG_PASSPHRASE}" \
            "${GITHUB_ENV}"
      - uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          ./hack/repos.sh ./charts
      - run: |
          make release-detect
      - run: |
          make release-package
      - run: |
          make release-upload CR_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - run: |
          make release-index CR_TOKEN=${{ secrets.GITHUB_TOKEN }}
