{{- if .Values.trigger.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ksvm.fullname" . }}-trigger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksvm.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
{{- if .Values.migrator.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ksvm.fullname" . }}-migrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksvm.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
